matchbox:
  resolve:
    baseurl: http://hapi.fhir.org/baseR5

spring:
  application:
    name: matchbox-server
  datasource:
    url: '${SPRING_DATASOURCE_URL}'
    username: '${SPRING_DATASOURCE_USERNAME}'
    password: '${SPRING_DATASOURCE_PASSWORD}'
    driverClassName: org.postgresql.Driver
    max-active: 15
    
hapi:
  fhir:
    version: R5
    server:
      path: /r5/*
    rest:
      server-name: matchbox Server
      server-version: 0.9.5
      implementation-description: FHIR Core Server
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
#    validation:
#      enabled: true
#      request-only: true
server:
  port: {$PORT:8080}