### @host = https://test.fhir.ch/r4

@host = http://localhost:8080/r4


### Convert between XML STU3 to XML R4
POST {{host}}/$convert HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=3.0

<StructureDefinition xmlns="http://hl7.org/fhir">
  <fhirVersion value="3.0.1"/>
</StructureDefinition>


### Convert between JSON R4 to XML R4

POST {{host}}/$convert HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

{
    "resourceType": "Composition",
    "status": "final",
    "type": {
        "coding": [
            {
                "system": "http://loinc.org",
                "code": "11536-0",
                "display": "Nurse note"
            }
        ]
    }
}


### Convert between XML STU3 to XML R4
POST {{host}}/$convert HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

map "http://hl7.org/fhir/cda/mapping/BundleToCDA" = "FHIR Bundle to CDA"
uses "http://hl7.org/fhir/cda/StructureDefinition/ClinicalDocument" alias ClinicalDocument as target
uses "http://hl7.org/fhir/StructureDefinition/Bundle" alias Bundle as source
uses "http://hl7.org/fhir/StructureDefinition/Composition" alias Composition as source
imports "http://hl7.org/fhir/cda/mapping/fhirToCDATypes"
group BundleClinicalDocument(source source : Bundle, target target : ClinicalDocument) {
  source.identifier -> target.id "id";
  source.entry as entry then {
    entry.resource as resource where resource.ofType(FHIR.Composition) then CompositionClinicalDocument(source, resource, target);
  };
}
group CompositionClinicalDocument(source bundle : Bundle, source source : Composition, target target : ClinicalDocument) {
  source.language -> target.languageCode "languageCode";
  source.extension as extension where extension.url = 'http://hl7.org/fhir/cda/StructureDefinition/templateID' then {
    extension.valueIdentifier -> target.templateId "identifier";
  } "templateID";
  source.identifier -> target.setId "setID";
  source.type -> target.code "code";
  source.date -> target.effectiveTime "effectiveTime";
  source.title -> target.title;
  source.confidentiality -> target.confidentialityCode "confidentialityCode";
  source.event as srcEvent ->  target.documentationOf as doc,  doc.serviceEvent as event then {
    srcEvent.period -> event.effectiveTime;
  };
  source.section as section ->  target.component as comp,  comp.structuredBody as body,  body.component as secComp,  secComp.section as tgtSection then {
    section.extension as extension where extension.url = 'http://hl7.org/fhir/cda/StructureDefinition/templateID' then {
      extension.valueIdentifier -> tgtSection.templateId "identifier";
    } "templateID";
    section.code -> section.code;
    section.title -> tgtSection.title;
    section.text as srcText -> tgtSection.text as tgtText then {
      srcText.div -> tgtText;
    };
  } "sections";
}


### Convert between XML STU3 to XML R4
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

map "http://hl7.org/fhir/cda/mapping/BundleToCDA" = "FHIR Bundle to CDA"
uses "http://hl7.org/fhir/cda/StructureDefinition/ClinicalDocument" alias ClinicalDocument as target
uses "http://hl7.org/fhir/StructureDefinition/Bundle" alias Bundle as source
uses "http://hl7.org/fhir/StructureDefinition/Composition" alias Composition as source
imports "http://hl7.org/fhir/cda/mapping/fhirToCDATypes"
group BundleClinicalDocument(source source : Bundle, target target : ClinicalDocument) {
  source.identifier -> target.id "id";
  source.entry as entry then {
    entry.resource as resource where resource.ofType(FHIR.Composition) then CompositionClinicalDocument(source, resource, target);
  };
}
group CompositionClinicalDocument(source bundle : Bundle, source source : Composition, target target : ClinicalDocument) {
  source.language -> target.languageCode "languageCode";
  source.extension as extension where extension.url = 'http://hl7.org/fhir/cda/StructureDefinition/templateID' then {
    extension.valueIdentifier -> target.templateId "identifier";
  } "templateID";
  source.identifier -> target.setId "setID";
  source.type -> target.code "code";
  source.date -> target.effectiveTime "effectiveTime";
  source.title -> target.title;
  source.confidentiality -> target.confidentialityCode "confidentialityCode";
  source.event as srcEvent ->  target.documentationOf as doc,  doc.serviceEvent as event then {
    srcEvent.period -> event.effectiveTime;
  };
  source.section as section ->  target.component as comp,  comp.structuredBody as body,  body.component as secComp,  secComp.section as tgtSection then {
    section.extension as extension where extension.url = 'http://hl7.org/fhir/cda/StructureDefinition/templateID' then {
      extension.valueIdentifier -> tgtSection.templateId "identifier";
    } "templateID";
    section.code -> section.code;
    section.title -> tgtSection.title;
    section.text as srcText -> tgtSection.text as tgtText then {
      srcText.div -> tgtText;
    };
  } "sections";
}


###

@host = https://test.ahdis.ch

###
POST {{host}}/r4/StructureDefinition HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

{
  "resourceType" : "StructureDefinition",
  "url" : "http://www.csvonfhir.com/codevscovid19/StructureDefinition/CovidDataFinal",
  "name" : "Healthdata",
  "status" : "unknown",
  "kind" : "logical",
  "abstract" : false,
  "type" : "CovidDataFinal",
  "baseDefinition" : "http://hl7.org/fhir/StructureDefinition/Element",
  "derivation" : "specialization",
  "differential" : {
    "element" : [{
      "id" : "CovidDataFinal",
      "path" : "CovidDataFinal"
    },
    {
      "id" : "CovidDataFinal.id",
      "path" : "CovidDataFinal.id",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.user",
      "path" : "CovidDataFinal.user",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.age",
      "path" : "CovidDataFinal.age",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.gender",
      "path" : "CovidDataFinal.gender",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.nationality",
      "path" : "CovidDataFinal.nationality",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.country",
      "path" : "CovidDataFinal.country",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.canton",
      "path" : "CovidDataFinal.canton",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.location_zip",
      "path" : "CovidDataFinal.location_zip",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.thinks_sick",
      "path" : "CovidDataFinal.thinks_sick",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.close_infected",
      "path" : "CovidDataFinal.close_infected",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.usually_home",
      "path" : "CovidDataFinal.usually_home",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.contacted_hospital",
      "path" : "CovidDataFinal.contacted_hospital",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.tested",
      "path" : "CovidDataFinal.tested",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.positive_to_test",
      "path" : "CovidDataFinal.positive_to_test",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.risk",
      "path" : "CovidDataFinal.risk",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.works_in_health",
      "path" : "CovidDataFinal.works_in_health",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.smoker",
      "path" : "CovidDataFinal.smoker",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.pregnant",
      "path" : "CovidDataFinal.pregnant",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.family",
      "path" : "CovidDataFinal.family",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.day",
      "path" : "CovidDataFinal.day",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.temperature",
      "path" : "CovidDataFinal.temperature",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.coughing",
      "path" : "CovidDataFinal.coughing",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.sneezing",
      "path" : "CovidDataFinal.sneezing",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.throat_pain",
      "path" : "CovidDataFinal.throat_pain",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.fatigue",
      "path" : "CovidDataFinal.fatigue",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.breathing_impaired",
      "path" : "CovidDataFinal.breathing_impaired",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.headache",
      "path" : "CovidDataFinal.headache",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.diarrhea",
      "path" : "CovidDataFinal.diarrhea",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.nausea",
      "path" : "CovidDataFinal.nausea",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    },
    {
      "id" : "CovidDataFinal.loss_of_smell",
      "path" : "CovidDataFinal.loss_of_smell",
      "min" : 0,
      "max" : "1",
      "type" : [{
        "code" : "string"
      }]
    }]
  }
}

###
POST {{host}}/r4/StructureMap HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

map "http://hl7.org/fhir/StructureMap/CovidDataFinalMap" = "CovidDataFinalMap"
uses "http://www.csvonfhir.com/codevscovid19/StructureDefinition/CovidDataFinal" alias CovidDataFinal as source
uses "http://hl7.org/fhir/StructureDefinition/Patient" alias Patient as target
group csv(source src : CovidDataFinal, target tgt : Patient) {
    src.gender as gender where $this = 'F'  -> tgt.gender = 'female' "rule_a";
    src.gender as gender where $this = 'M'  -> tgt.gender = 'male' "rule_b";
}

###
POST {{host}}/r4/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/CovidDataFinalMap
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

{
  "resourceType": "CovidDataFinal",
  "country": "Switzerland",
  "gender": "F",
  "tested": "FALSE",
  "thinks_sick": "TRUE",
  "works_in_health": "FALSE",
  "loss_of_smell": "1",
  "smoker": "FALSE",
  "fatigue": "1",
  "coughing": "0",
  "sneezing": "1",
  "temperature": "36.5",
  "close_infected": "FALSE",
  "id": "1",
  "location_zip": "3008",
  "day": "01.04.2020",
  "pregnant": "FALSE",
  "throat_pain": "0",
  "positive_to_test": "FALSE",
  "diarrhea": "0",
  "contacted_hospital": "TRUE",
  "nausea": "0",
  "nationality": "Switzerland",
  "canton": "BE",
  "risk": "TRUE",
  "headache": "0",
  "family": "2",
  "user": "user_1",
  "age": "60",
  "usually_home": "FALSE",
  "breathing_impaired": "0"
}