@host = http://localhost:8080/r4

### validate a resource with no profile
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml
Accept: application/fhir+xml

<Patient xmlns="http://hl7.org/fhir">
	<text>
		<status value="generated" />
		<div xmlns="http://www.w3.org/1999/xhtml">
			Franz Muster, 10.2.197
		</div>
	</text>
  <extension url="http://hl7.org/fhir/StructureDefinition/patient-birthPlace">
    <valueAddress>
      <city value="Paris"/>
      <country value="Frankreich"/>
    </valueAddress>
  </extension>
	<name>
		<family value="Muster" />
		<given value="Franz" />
	</name>
	<gender value="male" />
	<birthDate value="1967-10-02" />
	<address>
		<line value="Leidensweg 10" />
		<city value="Specimendorf" />
		<postalCode value="9876" />
	</address>
</Patient>



###
POST {{host}} HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

{
  "resourceType": "Bundle",
  "id": "bundle-transaction",
  "meta": {
    "lastUpdated": "2014-08-18T01:43:30Z"
  },
  "type": "transaction",
  "entry": [
    {
      "resource": {
        "resourceType" : "ImplementationGuide",
        "version" : "dev",
        "packageId": "hl7.fhir.cda"
      },
      "request": {
        "method": "POST"
      }
    },
    {
      "resource": {
        "resourceType" : "ImplementationGuide",
        "version" : "dev",
        "packageId": "ch.fhir.ig.ch-emed"
      },
      "request": {
        "method": "POST"
      }
    }
  ]
}
### Get all implementation guides
GET {{host}}/StructureDefinition/ch-core-composition-epr HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+json

### Get all implementation guides
GET {{host}}/ImplementationGuide HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+json

### Get all implementation guides
GET {{host}}/ImplementationGuide/ch%2Efhir%2Eig%2Ech%2Dcore HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+json

### Implementation Guide ch.fhir.ig.ch-core
POST {{host}}/ImplementationGuide HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

{
  "resourceType" : "ImplementationGuide",
  "version" : "current",
  "packageId": "ch.fhir.ig.ch-core"
}

### Implementation Guide ch.fhir.ig.ch-core
POST {{host}}/ImplementationGuide HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

{
  "resourceType" : "ImplementationGuide",
  "version" : "dev",
  "packageId": "ch.fhir.ig.ch-epr-term"
}

### Implementation Guide hl7.fhir.cda
POST {{host}}/ImplementationGuide HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

{
  "resourceType" : "ImplementationGuide",
  "version" : "dev",
  "packageId": "hl7.fhir.cda"
}


### Implementation Guide hl7.fhir.cda
POST {{host}}/ImplementationGuide HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

{
  "resourceType" : "ImplementationGuide",
  "version" : "dev",
  "packageId": "ch.fhir.ig.ch-emed"
}


### validate a resource with a profile embedded in meta
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml
Accept: application/fhir+xml

<Patient xmlns="http://hl7.org/fhir">
  <meta>
    <profile value="http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-patient"/>
  </meta>
	<text>
		<status value="generated" />
		<div xmlns="http://www.w3.org/1999/xhtml">
			Franz Muster, 10.2.197
		</div>
	</text>
   <extension url="http://hl7.org/fhir/StructureDefinition/patient-birthPlace">
    <valueAddress>
      <city value="Paris"/>
      <country value="Frankreich"/>
    </valueAddress>
  </extension>
	<name>
		<family value="Muster" />
		<given value="Franz" />
	</name>
	<gender value="male" />
	<birthDate value="1967-10-02" />
	<address>
		<line value="Leidensweg 10" />
		<city value="Specimendorf" />
		<postalCode value="9876" />
	</address>
</Patient>

### validate a resource with a profile
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-patient HTTP/1.1
Content-Type: application/fhir+xml
Accept: application/fhir+xml

<Patient xmlns="http://hl7.org/fhir">
	<text>
		<status value="generated" />
		<div xmlns="http://www.w3.org/1999/xhtml">
			Franz Muster, 10.2.197
		</div>
	</text>
   <extension url="http://hl7.org/fhir/StructureDefinition/patient-birthPlace">
    <valueAddress>
      <city value="Paris"/>
      <country value="Frankreich"/>
    </valueAddress>
  </extension>
   <extension url="http://hl7.org/fhir/StructureDefinition/patient-birthPlace">
    <valueAddress>
      <city value="Paris"/>
      <country value="Frankreich"/>
    </valueAddress>
  </extension>
	<name>
		<family value="Muster" />
		<given value="Franz" />
	</name>
	<gender value="male" />
	<birthDate value="1967-10-02" />
	<address>
		<line value="Leidensweg 10" />
		<city value="Specimendorf" />
		<postalCode value="9876" />
	</address>
</Patient>

### Parse a map and convert it to a StructureMap
POST {{host}}/$validate HTTP/1.1
Content-Type: application/json

{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "map",
      "valueString": "map \"http://ahdis.ch/fhir/mappingtutorial/qr2pat1\" = \"mapping tutorial questionnairetopat\"\nuses \"http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse\" alias QuestionnaireResponse as source\nuses \"http://hl7.org/fhir/StructureDefinition/Patient\" alias Patient as target\ngroup QuestionnaireResponse(source src : QuestionnaireResponse, target tgt : Patient)\n{\n src -> tgt.gender = 'male' \"Simple Assignment\";\n}"
    }, {
      "name": "updateOrCreate",
      "valueBoolean": true
    }
 ]
}


### Create a StructureMap
POST {{host}}/StructureMap HTTP/1.1
Content-Type: application/json

{
  "resourceType": "StructureMap",
  "url": "http://ahdis.ch/fhir/mappingtutorial/qr2pat1",
  "name": "mapping tutorial questionnairetopat",
  "status": "draft",
  "structure": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse",
      "mode": "source",
      "alias": "QuestionnaireResponse"
    },
    {
      "url": "http://hl7.org/fhir/StructureDefinition/Patient",
      "mode": "target",
      "alias": "Patient"
    }
  ],
  "group": [
    {
      "name": "QuestionnaireResponse",
      "typeMode": "none",
      "input": [
        {
          "name": "src",
          "type": "QuestionnaireResponse",
          "mode": "source"
        },
        {
          "name": "tgt",
          "type": "Patient",
          "mode": "target"
        }
      ],
      "rule": [
        {
          "name": "SimpleAssignment",
          "source": [
            {
              "context": "src"
            }
          ],
          "target": [
            {
              "context": "tgt",
              "contextType": "variable",
              "element": "gender",
              "transform": "copy",
              "parameter": [
                {
                  "valueString": "male"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

### Call the transform operation (you need to post first the StructureMap to the server)
POST {{host}}/StructureMap/$transform?source=http://ahdis.ch/fhir/mappingtutorial/qr2pat1 HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

{
  "resourceType": "QuestionnaireResponse",
  "status": "in-progress",
  "item": [
      {
        "linkId": "patient",
        "text": "Patient",
        "item": [
          {
            "linkId": "patient.lastname",
            "text": "Name",
            "answer": [
              {
                "valueString": "Egger"
              }
            ]
          },
          {
            "linkId": "patient.firstname",
            "text": "Vorname",
            "answer": [
              {
                "valueString": "Oliver"
              }
            ]
          },
          {
            "linkId": "patient.sex",
            "text": "Geschlecht",
            "answer": [
              {
                "valueString": "female"
              }
            ]
          }
        ]
      }
    ]
}

### Get stored StructureMaps
GET {{host}}/StructureMap/?_format=xml


### Get stored StructureMaps
GET {{host}}/Patient/1


### Convert operaton

POST {{host}}/$convert HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/xml+fhir;fhirVersion=3.0

<?xml version="1.0" encoding="UTF-8"?>
<StructureDefinition xmlns="http://hl7.org/fhir">
  <id value="chmed16af-condition-risks"/>
  <url value="http://chmed16af.emediplan.ch/fhir/StructureDefinition/chmed16af-condition-risks" />
  <version value="1.0.0" />
  <name value="Risks"/>
  <title value="Risks"/>
  <status value="draft" />
  <publisher value="IG eMediplan" />
  <contact>
    <telecom>
      <system value="url"/>
      <value value="http://www.emediplan.ch"/>
    </telecom>
  </contact>
  <description value="Profile on Condition for Risks"/>
  <fhirVersion value="3.0.1"/>
  <mapping>
    <identity value="CHMED16A"/>
    <uri value="http://emediplan.ch/chmed16a"/>
    <name value="Mapping to CHMED16A"/>
  </mapping>
  <kind value="resource"/>
  <abstract value="false"/>
  <type value="Condition"/>
  <baseDefinition value="http://hl7.org/fhir/StructureDefinition/Condition"/>
  <derivation value="constraint"/>
  <differential>
    <element id="Condition">
      <path value="Condition"/>
      <short value="Detailed information about conditions, problems or diagnoses"/>
      <definition value="A clinical condition, problem, diagnosis, or other event, situation, issue, or clinical concept that has risen to a level of concern."/>
      <min value="0"/>
      <max value="*"/>
      <mapping>
        <identity value="CHMED16A"/>
        <map value="MedicalData.RG (RiskCategory)"/>
      </mapping>
    </element>
    <element id="Condition.identifier">
      <path value="Condition.identifier"/>
      <short value="External Ids for this condition"/>
      <definition value="This records identifiers associated with this condition that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropriate (e.g. in CDA documents, or in written / printed documentation)."/>
      <requirements value="Need to allow connection to a wider workflow."/>
      <min value="0"/>
      <max value="*"/>
    </element>
    <element id="Condition.clinicalStatus">
      <path value="Condition.clinicalStatus"/>
      <short value="active | recurrence | inactive | remission | resolved"/>
      <definition value="The clinical status of the condition."/>
      <min value="1"/>
      <max value="1"/>
      <type>
        <code value="code"/>
      </type>
      <fixedCode value="active" />
    </element>
    <element id="Condition.verificationStatus">
      <path value="Condition.verificationStatus"/>
      <short value="provisional | differential | confirmed | refuted | entered-in-error | unknown"/>
      <definition value="The verification status to support the clinical status of the condition."/>
      <comment value="verificationStatus is not required.  For example, when a patient has abdominal pain in the ED, there is not likely going to be a verification status."/>
      <min value="0"/>
      <max value="0"/>
      <type>
        <code value="code"/>
      </type>
    </element>
    <element id="Condition.category">
      <path value="Condition.category"/>
      <short value="problem-list-item | encounter-diagnosis"/>
      <definition value="A category assigned to the condition."/>
      <comment value="The categorization is often highly contextual and may appear poorly differentiated or not very useful in other contexts."/>
      <min value="1"/>
      <max value="1"/>
      <type>
        <code value="CodeableConcept"/>
      </type>
      <binding>
        <extension url="http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName">
          <valueString value="ConditionCategory"/>
        </extension>
        <strength value="required"/>
        <description value="A category assigned to the condition."/>
        <valueSetReference>
          <reference value="http://chmed16af.emediplan.ch/fhir/ValueSet/chmed16af-valueset-risks-category"/>
        </valueSetReference>
      </binding>
      <mapping>
        <identity value="CHMED16A"/>
        <map value="RiskCatgory"/>
      </mapping>
    </element>
    <element id="Condition.severity">
      <path value="Condition.severity"/>
      <short value="Subjective severity of condition"/>
      <definition value="A subjective assessment of the severity of the condition as evaluated by the clinician."/>
      <comment value="Coding of the severity with a terminology is preferred, where possible."/>
      <min value="0"/>
      <max value="0"/>
      <type>
        <code value="CodeableConcept"/>
      </type>
    </element>
    <element id="Condition.code">
      <path value="Condition.code"/>
      <short value="Identification of the risk for that category."/>
      <definition value="Identification of the risk for that category. If the risk category is specified without any risk specified in the code, the entire risk category is considered as explicitly excluded for the current patient. If the risk category does not exist,the risks are considered as unknown for the patient."/>
      <requirements value="0..1 to account for primarily narrative only resources."/>
      <alias value="type"/>
      <min value="0"/>
      <max value="1"/>
      <type>
        <code value="CodeableConcept"/>
      </type>
      <isSummary value="true"/>
      <binding>
        <extension url="http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName">
          <valueString value="ConditionKind"/>
        </extension>
        <strength value="required"/>
        <description value="Identification of risk"/>
        <valueSetReference>
          <reference value="http://chmed16af.emediplan.ch/fhir/ValueSet/chmed16af-valueset-risks-cdscode"/>
        </valueSetReference>
      </binding>
      <mapping>
        <identity value="CHMED16A"/>
        <map value="risk"/>
      </mapping>
    </element>
    <element id="Condition.bodySite">
      <path value="Condition.bodySite"/>
      <short value="Anatomical location, if relevant"/>
      <definition value="The anatomical location where this condition manifests itself."/>
      <comment value="Only used if not implicit in code found in Condition.code. If the use case requires attributes from the BodySite resource (e.g. to identify and track separately) then use the standard extension [body-site-instance](extension-body-site-instance.html).  May be a summary code, or a reference to a very precise definition of the location, or both."/>
      <min value="0"/>
      <max value="0"/>
      <type>
        <code value="CodeableConcept"/>
      </type>
    </element>
    <element id="Condition.subject">
      <path value="Condition.subject"/>
      <short value="Who has the condition?"/>
      <definition value="Indicates the patient or group who the condition record is associated with."/>
      <requirements value="Group is typically used for veterinary or public health use cases."/>
      <alias value="patient"/>
      <min value="1"/>
      <max value="1"/>
    </element>
    <element id="Condition.context">
      <path value="Condition.context"/>
      <short value="Encounter or episode when condition first asserted"/>
      <definition value="Encounter during which the condition was first asserted."/>
      <comment value="This record indicates the encounter this particular record is associated with.  In the case of a &quot;new&quot; diagnosis reflecting ongoing/revised information about the condition, this might be distinct from the first encounter in which the underlying condition was first &quot;known&quot;."/>
      <alias value="encounter"/>
      <min value="0"/>
      <max value="0"/>
    </element>
    <element id="Condition.onset[x]">
      <path value="Condition.onset[x]"/>
      <short value="Estimated or actual date,  date-time, or age"/>
      <definition value="Estimated or actual date or date-time  the condition began, in the opinion of the clinician."/>
      <comment value="Age is generally used when the patient reports an age at which the Condition began to occur."/>
      <min value="0"/>
      <max value="0"/>
    </element>
    <element id="Condition.abatement[x]">
      <path value="Condition.abatement[x]"/>
      <short value="If/when in resolution/remission"/>
      <definition value="The date or estimated date that the condition resolved or went into remission. This is called &quot;abatement&quot; because of the many overloaded connotations associated with &quot;remission&quot; or &quot;resolution&quot; - Conditions are never really resolved, but they can abate."/>
      <comment value="There is no explicit distinction between resolution and remission because in many cases the distinction is not clear. Age is generally used when the patient reports an age at which the Condition abated.  If there is no abatement element, it is unknown whether the condition has resolved or entered remission; applications and users should generally assume that the condition is still valid.  When abatementString exists, it implies the condition is abated."/>
      <min value="0"/>
      <max value="0"/>
    </element>
    <element id="Condition.assertedDate">
      <path value="Condition.assertedDate"/>
      <short value="Date record was believed accurate"/>
      <definition value="The date on which the existance of the Condition was first asserted or acknowledged."/>
      <comment value="The assertedDate represents the date when this particular Condition record was created in the EHR, not the date of the most recent update in terms of when severity, abatement, etc. were specified.  The date of the last record modification can be retrieved from the resource metadata."/>
      <min value="0"/>
      <max value="0"/>
      <type>
        <code value="dateTime"/>
      </type>
    </element>
    <element id="Condition.asserter">
      <path value="Condition.asserter"/>
      <short value="Person who asserts this condition"/>
      <definition value="Individual who is making the condition statement."/>
      <min value="0"/>
      <max value="0"/>
    </element>
    <element id="Condition.stage">
      <path value="Condition.stage"/>
      <short value="Stage/grade, usually assessed formally"/>
      <definition value="Clinical stage or grade of a condition. May include formal severity assessments."/>
      <min value="0"/>
      <max value="0"/>
      <type>
        <code value="BackboneElement"/>
      </type>
    </element>
    <element id="Condition.evidence">
      <path value="Condition.evidence"/>
      <short value="Supporting evidence"/>
      <definition value="Supporting Evidence / manifestations that are the basis on which this condition is suspected or confirmed."/>
      <comment value="The evidence may be a simple list of coded symptoms/manifestations, or references to observations or formal assessments, or both."/>
      <min value="0"/>
      <max value="0"/>
      <type>
        <code value="BackboneElement"/>
      </type>
    </element>
    <element id="Condition.note">
      <path value="Condition.note"/>
      <short value="Additional information about the Condition"/>
      <definition value="Additional information about the Condition. This is a general notes/comments entry  for description of the Condition, its diagnosis and prognosis."/>
      <min value="0"/>
      <max value="0"/>
      <type>
        <code value="Annotation"/>
      </type>
    </element>
  </differential>
</StructureDefinition>




###

curl --request POST \
  --url 'http://localhost:8080/r4/$convert' \
  --header 'Content-Type: application/fhir+xml; fhirVersion=3.0' \
  --header 'Accept: application/fhir+xml' \
  --http1.1 \
  --data '@/Users/oliveregger/Documents/github/chmed16af/resources/structuredefinition/chmed16af-dosequantityto.xml' \
  -o '/Users/oliveregger/Documents/github/chmed16af/resources/structuredefinition/chmed16af-dosequantityto.xml'

###

curl --request POST \
  --url 'http://localhost:8080/r4/$convert' \
  --header 'Content-Type: application/fhir+xml; fhirVersion=3.0' \
  --header 'Accept: application/fhir+xml' \
  --http1.1 \
  --data '@/Users/oliveregger/Documents/github/chmed16af/resources/patient/chmed16af-m.xml' \
  -o '/Users/oliveregger/Documents/github/chmed16af/resources/structuredefinition/chmed16af-dosequantityto.xml'

###

POST {{host}}/$convert HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/plain

map "http://ahdis.ch/fhir/mappingtutorial/patient/gender" = "mapping tutorial patient gender"

uses "http://hl7.org/fhir/StructureDefinition/Patient" alias Patient as source
uses "http://hl7.org/fhir/StructureDefinition/Patient" alias Patient as target

group Patient(source src : Patient, target tgt : Patient) {
   src.gender as v -> tgt.gender = v "code-value";
   src.birthDate as v -> tgt.birthDate = v "code-value";
}


### @host = http://localhost:8080/r4


### Transaction

GET {{host}}/$get-resource-counts HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/xml+fhir

### Transaction

POST {{host}}/ HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/xml+fhir

<Bundle xmlns="http://hl7.org/fhir">
  <id value="bundle-transaction"/> 
<!--    this example bundle is a transaction     -->
  <meta> 
    <lastUpdated value="2014-08-18T01:43:30Z"/> 
  <!--    when the transaction was constructed    -->
  </meta> 
  <type value="transaction"/> 
<!--    now, each entry is an action to take in the transaction    -->
  <entry> 
    <fullUrl value="urn:uuid:61ebe359-bfdc-4613-8bf2-c5e300945f0a"/> 
    <resource> 
    <!--    a simple create operation    -->
    <!--    first, the resource to create    -->
      <Patient> 
        <id value="d6" />
        <text> 
          <status value="generated"/> 
          <div xmlns="http://www.w3.org/1999/xhtml">Some narrative</div> 
        </text> 
        <active value="true"/> 
        <name> 
          <use value="official"/> 
          <family value="Chalmers"/> 
          <given value="Peter"/> 
          <given value="James"/> 
        </name> 
        <gender value="male"/> 
        <birthDate value="1974-12-25"/> 
      </Patient> 
    </resource> 
     <!--    now, details about the action to take with the resource    -->
    <request> 
    <!--    POST to [base]/Patient - that's a create    -->
      <method value="PUT"/> 
    <!--    actually, in a transaction, you don't specify the [base], 
         so [base]/Patient becomes just 'Patient':    -->
      <url value="Patient/d6"/>
    </request> 
  </entry> 
  </Bundle>


###

curl --request GET \
  --url 'http://localhost:8080/r4/Composition/1/$document' \
  --header 'Accept: application/fhir+xml' \
  --http1.1 \
  -o '/Users/oliveregger/Documents/github/chmed16af/resources/bundle/chmed16af-mp-bundle-s01.xml'

### Parse a map and convert it to a StructureMap
POST {{host}}/$convert HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/xml+fhir;fhirVersion=3.0

<Parameters xmlns="http://hl7.org/fhir">
  <parameter>
    <name value="input"/>
    <resource>
       <Patient xmlns="http://hl7.org/fhir">
	<id value="chmed16af-mp-patient-ext" />
	<meta>
		<profile value="http://chmed16af.emediplan.ch/fhir/StructureDefinition/chmed16af-mp-patient" />
	</meta>
	<text>
		<status value="generated" />
		<div xmlns="http://www.w3.org/1999/xhtml">Maxima, Matter, geb 1981-01-12						
		</div>
	</text>
	<extension url="http://chmed16af.emediplan.ch/fhir/StructureDefinition/PrivateFieldNameSample">
		<valueString value="PrivateFieldValueSample" />
	</extension>
	<identifier>
		<system value="urn:oid:2.16.756.5.30.1.123.100.1.1.1"/>
		<value value="vekano" />
	</identifier>
	<name>
		<family value="Matter" />
		<given value="Maxima" />
	</name>
	<telecom>
		<system value="phone" />
		<value value="+41588512600" />
		<use value="home" />
	</telecom>
	<gender value="female" />
	<birthDate value="1981-01-12" />
	<address>
		<line value="Untermattweg 8" />
		<city value="Bern" />
		<postalCode value="3027" />
	</address>
	<communication>
		<language>
			<coding>
				<system value="urn:ietf:bcp:47" />
				<code value="de-CH" />
				<display value="German (Region=Switzerland)" />
			</coding>
		</language>
		<preferred value="true" />
	</communication>
</Patient>
    </resource>
  </parameter>
  <parameter>
    <name value="from"/>
    <valueUri value="0.1.0"/>
  </parameter>
  <parameter>
    <name value="to"/>
    <valueCode value="0.2.0"/>
  </parameter>
</Parameters>