hapi:
  fhir:
    version: R4
    server:
      path: /r4/*
    rest:
      server-name: matchbox ahdis
      server-version: 1.0.0
      implementation-description: FHIR Core Server
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: false
      request-only: true
    igs:
      -
        url: http://fhir.ch/ig/ch-epr-term/2.0.4/package.tgz
        name: ch.fhir.ig.ch-epr-term
        version: 2.0.4
      -
        url: http://fhir.ch/ig/ch-core/1.0.0/package.tgz
        name: ch.fhir.ig.ch-core
        version: 1.0.0
      -
        url: http://fhir.ch/ig/ch-emed/0.1.0/package.tgz
        name: ch.fhir.ig.ch-emed
        version: 0.1.0
      -
        url: http://fhir.ch/ig/ch-atc/3.1.0/package.tgz
        name: ch.fhir.ig.ch-atc
        version: 3.1.0
      -
        url: http://fhir.ch/ig/ch-epr-mhealth/0.1.0/package.tgz
        name: ch.fhir.ig.ch-epr-mhealth
        version: 0.1.0
logging:
  level:
    ch.ahdis: debug
jpa:
  scheduling-disabled: true
  subscription-enabled: false
  allow-external-references: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: target/lucenefiles
      hibernate.search.lucene_version: LUCENE_CURRENT
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
      hibernate.search.autoregister_listeners: false
      hibernate.search.indexing_strategy: manual
  h2:
    console:
      enabled: true 