spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: target/lucenefiles
      hibernate.search.lucene_version: LUCENE_CURRENT
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory

  h2:
    console:
      enabled: true
hapi:
  fhir:
    version: R4
    server:
      path: /r4/*
    rest:
      server-name: matchbox ahdis
      server-version: 1.0.0
      implementation-description: FHIR Core Server
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
    jpa:
      scheduling-disabled: true
      subscription-enabled: false
      allow-external-references: true 
logging:
  level:
    ca.uhn.fhir.jaxrs: debug
    ch.ahdis: debug
server:
  tomcat:
    max-threads: 5