spring:
  application:
    name: matchbox
hapi:
  fhir:
    version: R4
    server:
      path: /r4/*
    rest:
      server-name: matchbox ahdis
      server-version: 1.0.0
      implementation-description: FHIR Core Server
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
logging:
  level:
    ca.uhn.fhir.jaxrs: debug
    ch.ahdis: debug
server:
  port: 8080