matchbox:
  resolve:
    baseurl: http://hapi.fhir.org/baseR4

spring:
  application:
    name: matchbox
hapi:
  fhir:
    version: R4
    server:
      path: /r4/*
    rest:
      server-name: matchbox ahdis
      server-version: 0.9.5
      implementation-description: FHIR Core Server
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
    implementationguides:
      -
       name: hl7.fhir.pubpack
       version: 0.0.7
      -
       name: hl7.fhir.xver-extensions
       version: 0.0.5
      -
       name: hl7.terminology.r4
       version: 2.0.0
      -
        name: ch.fhir.ig.ch-epr-term
        version: 2.0.5
      -
        name: ch.fhir.ig.ch-core
        version: 2.0.0
      -
        name: ch.fhir.ig.ch-vacd
        version: 1.0.0
      -
        name: ch.fhir.ig.ch-emed
        version: 1.0.0
      -
        name: ch.fhir.ig.ch-atc
        version: 3.1.0
      -
        name: ch.fhir.ig.ch-orf
        version: 0.10.0
      -
        name: ch.fhir.ig.ch-rad-order
        version: 0.1.0
      -
        name: ch.fhir.ig.ch-etoc
        version: 0.1.0
      -
        name: ch.fhir.ig.ch-epr-mhealth
        version: 0.2.0
      -
        name: hl7.fhir.cda
        version: dev
      -
        name: ch.fhir.ig.cda-fhir-maps
        version: 0.2.0
server:
  port: 8080
    