matchbox:
  resolve:
    baseurl: http://hapi.fhir.org/baseR4

hapi:
  fhir:
    server:
      path: /r4/*
    rest:
      server-name: matchbox ahdis         
    implementationguides:
      -
       name: hl7.fhir.pubpack
       version: 0.0.7
      -
       name: hl7.fhir.xver-extensions
       version: 0.0.5
server:
  port: 8080