name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build_package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B compile package --file pom.xml
    - name: 'Tar files'
      run: tar -cvf package.tar target/matchbox-0.9.9-SNAPSHOT.jar
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: package.tar
        retention-days: 1
  build_docker:
    needs: build_package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: package
          path: download
      - name: 'UnTar files'
        run: |
        tar -tf download/package.tar
        tar -xvf download/package.tar target/matchbox-0.9.9-SNAPSHOT.jar 
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: /
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testing:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          stack: container
          docker_build_args: |
            JAR_FILE
        env:
          JAR_FILE: target/matchbox-0.9.9-SNAPSHOT.jar

